
language: c

os:
  - linux

env:
  global:
    - OPAMYES=true
    - OPAMJOBS=2
    - OPAMVERBOSE=true
    - OCAML_VERSION=4.07.0

addons:
  apt:
    packages:
      - m4
      # - opam
      - expect-dev # for unbuffer

cache:
  directories:
    - ${HOME}/.opam

install:
  # Download and use opam2
  - wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.0-beta6/opam-2.0.0-beta6-x86_64-linux
  - chmod +x ${HOME}/opam
  - ${HOME}/opam init --compiler=${OCAML_VERSION}
  - eval `${HOME}/opam config env`
  - ${HOME}/opam switch ${OCAML_VERSION}
  - eval `${HOME}/opam config env`
  - ${HOME}/opam install ocamlfind extlib menhir
  - ${HOME}/opam install js_of_ocaml js_of_ocaml-ppx js_of_ocaml-lwt

before_script:
  - unbuffer ./build.sh murderFiles

script:
  - unbuffer ./build.sh && mv main.js web/
  - unbuffer ./build.sh tests.byte && ./tests.byte

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  on:
    branch: master

