
language: c
env:
  - OCAML_VERSION=4.07.0
addons:
  apt:
    packages:
      - bubblewrap
      - opam

before_install:
  # Download and use opam2
  - wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.3/opam-2.0.3-x86_64-linux
  - chmod +x ${HOME}/opam
  # Some opam boilerplate
  - export OPAMYES=1
  - export OPAMJOBS=2
  # Init opam, and the default switch with the right ocaml version
  - ${HOME}/opam init --compiler=${OCAML_VERSION}
  - eval `${HOME}/opam config env`
  - export OPAMVERBOSE=1
  - opam switch
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam install ocamlfind extlib js_of_ocaml

install:
  - ./build.sh && mv main.js web/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages

