
language: c
env:
  global:
    - OPAMYES=true
    - OPAMJOBS=2
    - OPAMVERBOSE=true
    - OCAML_VERSION=4.07.0
addons:
  apt:
    packages:
      - m4
      # - opam

cache:
  directories:
    - ${HOME}/.opam

install:
  # Download and use opam2
  - wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.0-beta6/opam-2.0.0-beta6-x86_64-linux
  - chmod +x ${HOME}/opam
  - ${HOME}/opam init --compiler=${OCAML_VERSION}
  - eval `${HOME}/opam config env`
  - ${HOME}/opam switch ${OCAML_VERSION}
  - eval `${HOME}/opam config env`
  - ${HOME}/opam install ocamlfind extlib js_of_ocaml

script:
  - ./build.sh && mv main.js web/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  # keep-history: true
  on:
    branch: master

